[package]
name = "fdf"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Fast file duplicate finder core library"

[dependencies]
blake3 = "1.8.2"
hex = "0.4.3"
indicatif = "0.18.0"
lazy_static.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
sha2 = { version = "0.10.9", features = ["asm"] }
string_cache = "0.9.0"
tracing.workspace = true
twox-hash = "2.1.1"
walkdir = "2.5.0"