[package]
name = "fdf"
version = "0.3.0"
authors = ["Aarni Koskela <akx@iki.fi>"]
edition = "2021"

[dependencies]
clap = "2.33.0"
hex = "0.4.1"
humansize = "1.1.0"
indicatif = "0.14.0"
rayon = "1.3.0"
regex = "1.3.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
sha2 = "0.8.1"
string_cache = "0.8.0"
walkdir = "2.3.1"
murmur3 = "0.5.1"
