[package]
name = "fdf"
version = "0.1.0"
authors = ["Aarni Koskela <akx@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
regex = "1"
rayon = "1.1"
walkdir = "2.2"