[workspace]
members = ["crates/fdf", "crates/fdf_cli"]
default-members = ["crates/fdf_cli"]
resolver = "2"

[workspace.package]
version = "0.5.0"
authors = ["Aarni Koskela <akx@iki.fi>"]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.98"
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
