[package]
name = "fdf"
version = "0.1.0"
authors = ["Aarni Koskela <akx@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
hashbrown = { version = "0.5", features = ["rayon"] }
hex = "0.3.2"
humansize = "1.1"
indicatif = "0.11.0"
rayon = "1.1"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8.0"
string_cache = "0.7"
walkdir = "2.2"