[package]
name = "fdf"
version = "0.1.0"
authors = ["Aarni Koskela <akx@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
hashbrown = { version = "0.6.2", features = ["rayon"] }
hex = "0.4.0"
humansize = "1.1.0"
indicatif = "0.12.0"
rayon = "1.2.0"
regex = "1.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
sha2 = "0.8.0"
string_cache = "0.8.0"
walkdir = "2.2.9"
