name: Build Release

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        if: runner.os != 'Windows'
        with:
          name: fdf-${{ matrix.os }}
          path: target/release/fdf
      - uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: fdf-${{ matrix.os }}.exe
          path: target/release/fdf.exe
